# Generated by Django 4.2.13 on 2024-07-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(choices=[('BSc', 'Bachelor of Science'), ('MSc', 'Master of Science')], max_length=3, unique=True),
        ),
    ]
