# Generated by Django 4.2.13 on 2024-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_staff_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='status',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
    ]
