# Generated by Django 4.2.13 on 2024-07-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_department_semester_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='program',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='department',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='program',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_id',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
